# Generated by Django 4.2.5 on 2023-10-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=20)),
                ('nivel', models.IntegerField()),
                ('liga', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='fechadecreacion',
        ),
        migrations.DeleteModel(
            name='nickname',
        ),
        migrations.DeleteModel(
            name='rango',
        ),
    ]
