# Generated by Django 4.2.5 on 2023-10-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_personaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='apellido',
        ),
    ]
