# Generated by Django 4.2.5 on 2023-10-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_rename_contraseña_usuario_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
