# Generated by Django 4.2.5 on 2023-10-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
