# Generated by Django 4.2.5 on 2023-10-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_alter_usuario_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='vestimenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('partesuperior', models.ImageField(blank=True, null=True, upload_to='ropa')),
                ('parteposterior', models.ImageField(blank=True, null=True, upload_to='ropa')),
                ('calzado', models.ImageField(blank=True, null=True, upload_to='ropa')),
            ],
        ),
    ]
