# Generated by Django 4.2.5 on 2023-10-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_vestimenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('daño', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='armas')),
            ],
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
