# Generated by Django 4.2.5 on 2023-10-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_arma_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='escudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('durabilidad', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='escudos')),
            ],
        ),
    ]
