# Generated by Django 4.2.5 on 2023-10-24 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0011_escudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaje',
            old_name='name',
            new_name='nombre',
        ),
    ]
